### ISSUE TITLE
Add social media or website link to the Readme 

### ISSUE THREAD

**Issue by jacknsoda** [john-and-jon/App-Prototype#4]
Hey 

@JohnSargant can you add a link to your *social media*.

Thanks!

**Comment by JohnSargant** [comment]
thanks! You are *cool*

**Comment by JohnSargant** [comment]
I will never do what you ask

**Comment by jacknsoda** [comment]
I WILL MAKE YOU!

**Comment by JohnSargant** [comment]
This is closed. quit asking!!!!
